### ISSUE TITLE
Add -Djavax.xml.accessExternalDTD=all generally

### ISSUE THREAD

**Issue by jonashackt** [codecentric/cxf-spring-boot-starter-maven-plugin#10]
Description here: https://github.com/codecentric/cxf-spring-boot-starter/issues/22

**Comment by marcopaga** [comment]
Relevant documentation regarding this issue: http://openjdk.java.net/jeps/185 and https://jaxp.java.net/1.4/JAXP-Compatibility.html#JAXP_security

**Comment by marcopaga** [comment]
Too bad I used the codecentric/cxf-spring-boot-starter#22 id instead of the #10.

The fix is: a4d357ee6998e5a2c1488f94cc2dcf79d120231f

**Comment by marcopaga** [comment]
@jonashackt Any ETA for the next release? ;)
