### ISSUE TITLE
targetNamespace could not be extracted from WSDL file continue

### ISSUE THREAD

**Issue by marcinsienko** [codecentric/cxf-spring-boot-starter-maven-plugin#12]
Hi,

Is any chance to support also namespaces with "-" signs like:

 <xsd:schema elementFormDefault="qualified" targetNamespace="urn:microsoft-dynamics-schemas/page/customers" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

?

Thanks a lot.
Regards,
Marcin

**Comment by jonashackt** [comment]
Sure. We´ll have a look onto it and come back to you here.

**Comment by jonashackt** [comment]
@marcinsienko the code now also supports dashes - I´ll release the new 1.1.2 now, this will take some while, till it´s available through Maven Central (think, tomorrow it will be accessible :) ).

**Comment by marcinsienko** [comment]
Thanks a lot :).

Regards,
Marcin
