### ISSUE TITLE
targetNamespace could not be extracted from WSDL file more complicated issue

### ISSUE THREAD

**Issue by marcinsienko** [codecentric/cxf-spring-boot-starter-maven-plugin#14]
Hi again,

This issue is a little complicated. I have a project and try to generate classes from wsdl. i have targetNamespace: **http://webservice_v26.tag.crm.comarch.com/** and it not works beacuse of 

> targetNamespace could not be extracted from WSDL file

It is regexp issue i think but there is also more complicate issue. When I add second WSDL that has supported namespace **urn:microsoft-dynamics-schemas/page/customers** build process passed but assign the same wsdl location to both generated services:

- CustomersService
- TAGExternalAPIImplService

@WebServiceClient(name = "TAGExternalAPIImplService", targetNamespace = "http://webservice_v26.tag.crm.comarch.com/", wsdlLocation = **"/wsdl/Customers.wsdl"**)

@WebServiceClient(name = "Customers_Service", targetNamespace = "urn:microsoft-dynamics-schemas/page/customers", wsdlLocation = **"/wsdl/Customers.wsdl"**)

In TAGExternalAPIImplService it should be **/wsdl/tagExternalAPIv26.wsdl**

More support targetNamespace like http://webservice_v26.tag.crm.comarch.com/ also will be helpful. :)

Could you take a look at it in meantime please?
I use version 1.1.2.RELEASE.

Thanks a lot and regards,
Marcin

**Comment by jonashackt** [comment]
Sorry for the late reply. The implementation now also supports underscores like in your example http://webservice_v26.tag.crm.comarch.com/. I will release it soon, so I would appreciate if you could test it. 

Then we´ll have a look at the second problem you mentioned, ok?!

**Comment by jonashackt** [comment]
@marcinsienko the Plugin with 1.1.3.RELEASE is now released, but it will take a few hours till you could get it over Maven Central. Have fun :)

**Comment by marcinsienko** [comment]
Hi,

Sorry for late answer. I've just back from holiday and  I've a lot of work
to do :( . I'll try to check it during this weak.

Thanks a lot,
Marcin

2017-09-13 9:26 GMT+02:00 Jonas Hecht <notifications@github.com>:
