### ISSUE TITLE
How do I add implementation codes?

### ISSUE THREAD

**Issue by jadedevin13** [codecentric/cxf-spring-boot-starter-maven-plugin#18]
I can usually add implementation codes by adding `<extraarg>-impl</extraarg>` using [cxf codegen plugin](http://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html) How can I do it in this plugin?

http://cxf.apache.org/docs/wsdl-to-java.html

**Comment by kpuscas** [comment]
I have the same question with regards to adding xjc extensions.

thanks

**Comment by jonashackt** [comment]
Hi @jadedevin13 and @kpuscas - your question is related to the [cxf-codegen-plugin](http://cxf.apache.org/docs/maven-cxf-codegen-plugin-wsdl-to-java.html), but with our cxf-spring-boot-starter-maven-plugin we´re encapsulating the [jaxws-maven-plugin](http://www.mojohaus.org/jaxws-maven-plugin/), which is a different implementation.

Usually, you shouldn´t need extra arguments - this is abstracted away from the user. If you have a concrete argument, that you need, please file a new Issue especially for that - and we´ll have a look into it. 

Closing this for off topic.
