### ISSUE TITLE
Generation of JAX-B classfiles skipped

### ISSUE THREAD

**Issue by severinstrobl** [codecentric/cxf-spring-boot-starter-maven-plugin#19]
Due to an implementation detail of `findWsdl()`, the first WSDL file found in `mavenProject.getBasedir()` is selected:
https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin/blob/ce5fb2d2db001c04a25b39be54fb0aaa5c36de91/src/main/java/de/codecentric/cxf/BootCxfMojo.java#L193

This location is then passed on to `isWsdlLocatedInMainResources()` which tests the path for the occurrence of "/main/" || "\\main\\" in order to determine if the Java code should be generated. This test fails in some cases due to `FileUtils.listFiles()` not guaranteeing any specific order. In my case, a copy of the WSDL file in the output directory is returned as the first entry, leading to a failure of the test. As a consequence, steps 2 and 3 are skipped altogether and no code is generated.

As a fix, in addition to testing for "/main/" || "\\main\\", the path check should also exclude any files in the output directory.

**Comment by jonashackt** [comment]
Hey @severinstrobl, I will release the plugin soon, so you could use it in your projects.
