### ISSUE TITLE
exposes only one endpoint when requesting ?wsdl

### ISSUE THREAD

**Issue by obbyK** [codecentric/cxf-spring-boot-starter-maven-plugin#26]
I just started using your plugin. I created two endpoints but when I request the wsdl using the context set by "soap.service.base.url" e.g. http://127.0.0.1:8080/sp?wsdl, it only returns one service definition though there are two endpoints

**Comment by obbyK** [comment]
I have checked a little bit more and it seems the plugin only adds the `sei.and.webserviceclient.package.name` for the first wsdl it encounters in the resources folder, for the other wsdls, it does generate code but their packages are not added in the "cxf-spring-boot-maven.properties" for autodetection to pick them out

**Comment by jonashackt** [comment]
Hey @obbyK you're absolutely right that the https://github.com/codecentric/cxf-spring-boot-starter and it's companion plugin only support 1 WSDL per service. This is intended and already discussed here https://github.com/codecentric/cxf-spring-boot-starter/issues/10. TLDR: As we'll design the starter for a Microservice architecture, you should simple use more then one Spring Boot based services, if you need to address more then one web service. Therefore I close this issues now.
