### ISSUE TITLE
targetNamespace could not be extracted from WSDL file

### ISSUE THREAD

**Issue by VittorioZinno** [codecentric/cxf-spring-boot-starter-maven-plugin#8]
Hi Jonas

targetNamespace containing numbers like http://www.abc.ch/namespase/filsearch/v5 are not found.

My suggestion is to simplify the regex.

`private static final String REGEX_FIND_TARGET_NAMESPACE_CONTENT = "(?<=targetNamespace=\\")[:./a-zA-Z0-9]+(?=\\")";
`

OR

`private static final String REGEX_FIND_TARGET_NAMESPACE_CONTENT = "targetNamespace=\\"([^\\"]+)";`
and
`return matcher.group(1);`

What do you think?

Best regards

Vittorio

**Comment by jonashackt** [comment]
Thanks for reporting, we´ll fix that :)

**Comment by jonashackt** [comment]
Sorry for the long delay @VittorioZinno, fix is now out. We´ll release soon ;)

**Comment by jonashackt** [comment]
Release is out, should need some hours to be available over Maven central.
