### ISSUE TITLE
Passing optional parameters to the JAX-WS Maven Plugin 

### ISSUE THREAD

**Issue by nydi** [codecentric/cxf-spring-boot-starter-maven-plugin#9]
Hi Jonas

Thanks for creating the plugin!

I have to add the Soap headers as arguments of the Soap service Java method. This is possible with enabling the xadditionalHeaders parameter of the JAX-WS Maven Plugin. There are more parameters listed in http://www.mojohaus.org/jaxws-maven-plugin/wsimport-mojo.html. As i see, there is actual no way to passing such parameters to the JAX-WS Maven Plugin.

It would be more flexibel if it were possible passing the optional parameters from a configuration element in the pom.xml plugin definition to the JAX-WS Maven Plugin.

Or is there a way, passing these parameters?

Cheers
Dani

**Comment by jonashackt** [comment]
Hi Daniel, good to know someone finds it useful :)

It was originally created with the intention to hide the complexity of the configuration options the jaxws-maven-plugin has and to just have a Maven build plugin you just put into your build section and you´re done.

This intention is now challenged... Could you provide a sample-projekt on github where you demonstrate this scenario? I´am trying to decide, if it is a general scenario for more users and we should support that in our flow of https://github.com/codecentric/cxf-spring-boot-starter and maven plugin. I also try to get to know, if we should open the plugin in general for other configuration options or if we then need another solution.

**Comment by jonashackt** [comment]
Is there some progress here @nydi or should we close this issue?

**Comment by jonashackt** [comment]
I´ll close it now. If you ever want to come back into the discussion or just think, we need to implement a specific parameter - please open a new issue.

**Comment by kiranreddykasa** [comment]
This feature would be helpful

**Comment by junhuhdev** [comment]
Hi I'm having the same issue, are there any workarounds?
